rootProject.name = "designPatternPractice"
include("commandPattern")
include("factoryPattern")
include("abstractFactoryPattern")
include("builderPattern")
include("singletonPattern")
include("prototypePattern")
include("chainOfResponsibilityPattern")
include("statePattern")
include("templatePattern")
